// Skuteční obyvatelé Louky. Jména a povahy přebrané z nechmerust.org
// (stránka "Zvířecí obyvatelé"). Naučná fakta jsou ověřená a česky.
import type { AnimalDef } from "../types";

export const ANIMALS: AnimalDef[] = [
  // ---- DRŮBEŽ (ráno se vypouští, večer zavírá) ----------------------------
  {
    id: "pipinky",
    name: "Pipinky",
    species: "slepice",
    feedGroup: "drubez",
    personality: "Malí a roztomilí obyvatelé naší Louky.",
    fact: "Slepice se dorozumívají více než 30 různými zvuky a se svými kuřaty si „povídají“ už když jsou ještě ve vejci.",
    palette: { body: "#f0d06a", bodyDark: "#d0a838", belly: "#f7e6a8", detail: "#d96c3c", accent: "#b85c3c" },
  },
  {
    id: "husy",
    name: "Husy",
    species: "husa",
    feedGroup: "drubez",
    personality: "Strážkyně dvora — kdo přijde, ten to ví. Tvoří věrné páry.",
    fact: "Husy bývají věrné na celý život a v letové formaci „V“ si navzájem šetří síly — vedoucí se střídají.",
    palette: { body: "#f5f2ec", bodyDark: "#d8d2c4", belly: "#fbf9f4", detail: "#e89c3c", accent: "#d98c3c" },
  },
  {
    id: "kachny",
    name: "Kachny",
    species: "kachna",
    feedGroup: "drubez",
    personality: "Rozšťebetané a věčně u vody.",
    fact: "Kachní peří je voděodolné — kachna si ho maže tukem z kostrční žlázy, proto z něj voda steče.",
    palette: { body: "#8a7a5c", bodyDark: "#2d6a4f", belly: "#d8cbb0", detail: "#e8b84c", accent: "#3a5a8c" },
    variant: "mallard",
  },
  {
    id: "holoubci",
    name: "Holoubci",
    species: "holub",
    feedGroup: "drubez",
    personality: "Krásní ptáci, kteří přinášejí klid a harmonii.",
    fact: "Holubi trefí domů i ze stovek kilometrů — vnímají magnetické pole Země a orientují se i podle slunce.",
    palette: { body: "#b8bcc6", bodyDark: "#8a8e98", belly: "#e6e8ec", detail: "#d98c9c", accent: "#6a8cae" },
  },

  // ---- PRASATA (vařené krmivo) --------------------------------------------
  {
    id: "princezna",
    name: "Princezna",
    species: "prase",
    feedGroup: "prasata",
    personality:
      "Ušlechtilá černá kříženka divočáka, jejíž královská noblesa se při prvním zakručení v břiše promění v nezastavitelnou slintavou potopu.",
    fact: "Prasata patří mezi nejchytřejší zvířata — poznají se v zrcadle a v testech předčí i psy.",
    palette: { body: "#3a3330", bodyDark: "#211c1a", belly: "#5a4f49", detail: "#d98c8c", accent: "#2a2422" },
    variant: "boar",
  },
  {
    id: "flicek",
    name: "Flíček",
    species: "prase",
    feedGroup: "prasata",
    personality: "Prasík, co má rád drbání na bříšku.",
    fact: "Prasata se válí v bahně, protože nemají skoro žádné potní žlázy — bláto je chladí a chrání kůži před sluncem.",
    palette: { body: "#f3b9bf", bodyDark: "#e08c98", belly: "#f8d4d8", detail: "#d96c7c", accent: "#b85c3c" },
    variant: "spot",
  },

  // ---- STÁDO (seno: krávy, ovce, berani, osel, muflon) --------------------
  {
    id: "karel",
    name: "Karel",
    species: "osel",
    feedGroup: "stado",
    personality: "Hravý osel s velkým srdcem a lehce kousavou povahou.",
    fact: "Osli mají skvělou paměť a dožívají se 30–50 let. Nejsou tvrdohlaví — když se zastaví, obvykle zvažují nebezpečí.",
    palette: { body: "#9a9a9f", bodyDark: "#6d6d72", belly: "#d8d6d0", detail: "#45454a", accent: "#e8a0a0" },
  },
  {
    id: "yakul",
    name: "Yakul",
    species: "muflon",
    feedGroup: "stado",
    personality: "Rozverný mladý muflon, který objevuje, k čemu slouží rohy.",
    fact: "Muflon je nejmenší evropská divoká ovce. Mohutné stočené rohy beranů rostou celý život a prozradí i jejich věk.",
    palette: { body: "#8a5a36", bodyDark: "#5e3b22", belly: "#d9b48c", detail: "#e8e2d0", accent: "#3a2616" },
    variant: "rohy",
  },
  {
    id: "avala",
    name: "Avala",
    species: "krava",
    feedGroup: "stado",
    personality: "Mazlivá kráva, která miluje běhání po louce.",
    fact: "Krávy mají nejlepší kamarádky a stresují se, když je od nich někdo oddělí. Pamatují si přes 50 tváří.",
    palette: { body: "#f2efe9", bodyDark: "#2a2622", belly: "#f7f4ef", detail: "#f0b8a8", accent: "#2a2622" },
    variant: "strakata",
  },
  {
    id: "kveta",
    name: "Květa",
    species: "krava",
    feedGroup: "stado",
    personality: "Klidná kravka, co má ráda svůj klid a je věrnou společnicí Avaly.",
    fact: "Dojnice i kráva bez telete prožívají silné přátelské vazby — leží ráda vedle své oblíbené družky.",
    palette: { body: "#b07a4e", bodyDark: "#7d5234", belly: "#e7cbac", detail: "#f0b8a8", accent: "#5a3a22" },
    variant: "hneda",
  },
  {
    id: "pogo",
    name: "Pogo",
    species: "ovce",
    feedGroup: "stado",
    personality: "Energická ovčí kamarádka.",
    fact: "Ovce rozeznají až 50 obličejů — ovčích i lidských — a pamatují si je roky. Mají skoro kruhové vidění.",
    palette: { body: "#f4f0e8", bodyDark: "#d8d0c0", belly: "#faf7ef", detail: "#3a3330", accent: "#2a2622" },
    variant: "ovce",
  },
  {
    id: "lucinka",
    name: "Lucinka",
    species: "ovce",
    feedGroup: "stado",
    personality: "Veselá a přátelská ovčí babička.",
    fact: "Ovce jsou velmi družné — osamělá ovce strádá. Ve stádu se cítí bezpečně a navzájem se hlídají.",
    palette: { body: "#e8e2d6", bodyDark: "#ccc4b4", belly: "#f3efe6", detail: "#8a8276", accent: "#6a6258" },
    variant: "stara",
  },
  {
    id: "anaya",
    name: "Anaya",
    species: "ovce",
    feedGroup: "stado",
    personality: "Veselá a přátelská ovčí obyvatelka.",
    fact: "Ovčí vlna roste neustále — proto se ovce na jaře stříhá, aby jí v létě nebylo příliš horko.",
    palette: { body: "#f0ece2", bodyDark: "#d4ccbc", belly: "#f7f3ea", detail: "#463c30", accent: "#2e261c" },
    variant: "ovce",
  },
  {
    id: "eduard",
    name: "Eduard",
    species: "ovce",
    feedGroup: "stado",
    personality: "Důstojný a klidný člen naší zvířecí rodiny.",
    fact: "Beran dává rohy k dobru hlavně na jaře v době námluv — jinak je to klidný strážce stáda.",
    palette: { body: "#e8e0d0", bodyDark: "#cdc2ac", belly: "#f3eee2", detail: "#4a4036", accent: "#cdbf9c" },
    variant: "beran",
  },
  {
    id: "emil",
    name: "Emil",
    species: "ovce",
    feedGroup: "stado",
    personality: "Bezrohý (už) obyvatel Louky. Nehne se od Amálky.",
    fact: "Zvířata si tvoří nerozlučné páry. Emil a Amálka se drží spolu — odloučení by je oba stresovalo.",
    palette: { body: "#e4dccb", bodyDark: "#c8bfa8", belly: "#f0ebe0", detail: "#463c30", accent: "#2e261c" },
    variant: "bezrohy",
  },
  {
    id: "amalka",
    name: "Amálka",
    species: "ovce",
    feedGroup: "stado",
    personality: "Jemná a láskyplná obyvatelka Louky. Nehne se od Emila.",
    fact: "Ovce poznají náladu z výrazu tváře a raději se dívají na klidné, usměvavé obličeje než na rozzlobené.",
    palette: { body: "#f2eee4", bodyDark: "#d8d0c0", belly: "#f8f4ec", detail: "#463c30", accent: "#2e261c" },
    variant: "ovce",
  },
  {
    id: "kulich",
    name: "Kulich",
    species: "ovce",
    feedGroup: "stado",
    personality: "Milý a přátelský obyvatel naší Louky.",
    fact: "Ovce se navzájem oslovují bečením a jehňata poznají hlas své matky v celém stádu.",
    palette: { body: "#efe7d8", bodyDark: "#d3c9b6", belly: "#f5f0e6", detail: "#4a4036", accent: "#b8a888" },
    variant: "ovce",
  },
  {
    id: "konci",
    name: "Končí",
    species: "ovce",
    feedGroup: "stado",
    personality: "Zvědavý a aktivní člen naší komunity.",
    fact: "Ovce dokážou řešit jednoduché bludiště a pamatují si cestu k jídlu i po měsících.",
    palette: { body: "#ece4d4", bodyDark: "#d0c6b2", belly: "#f3eee2", detail: "#4a4036", accent: "#2e261c" },
    variant: "ovce",
  },

  // ---- MAZLÍCI (psi, kočky, králíci) --------------------------------------
  {
    id: "riky",
    name: "Riky",
    species: "pes",
    feedGroup: "mazlici",
    personality: "Hravý pes, který hlídá celou Louku.",
    fact: "Psi vnímají svět hlavně čichem — mají až 300 milionů čichových buněk, člověk jen kolem šesti.",
    palette: { body: "#c8884c", bodyDark: "#9a6233", belly: "#ecd6b8", detail: "#3a2a1c", accent: "#2a2018" },
    variant: "guard",
  },
  {
    id: "kesy",
    name: "Kesy",
    species: "pes",
    feedGroup: "mazlici",
    personality:
      "Vypadá jako obří chlupatý medvěd a má rozvážnost zenového mistra. Povely bere jen jako doporučení.",
    fact: "Velká pastevecká plemena jsou samostatná — byla šlechtěna, aby u stáda rozhodovala sama, i bez člověka.",
    palette: { body: "#ece4d2", bodyDark: "#c4b89c", belly: "#f5efe0", detail: "#6a5a44", accent: "#8a7a5a" },
    variant: "shaggy",
  },
  {
    id: "atila",
    name: "Atila",
    species: "pes",
    feedGroup: "mazlici",
    personality: "Věrná kamarádka a velká milovnice jídla.",
    fact: "Psi rozumějí lidským gestům — sledují, kam ukazujeme, což kromě nich umí málokteré zvíře.",
    palette: { body: "#2e2823", bodyDark: "#1a1712", belly: "#b07a4e", detail: "#0f0d0a", accent: "#8a5a30" },
    variant: "blacktan",
  },
  {
    id: "denis",
    name: "Denis",
    species: "pes",
    feedGroup: "mazlici",
    personality: "Velký průzkumník a velký mazel.",
    fact: "Psí nos pracuje i odděleně — každá nosní dírka „čichá“ zvlášť, a tak pozná, odkud pach přichází.",
    palette: { body: "#6a5a48", bodyDark: "#463a2c", belly: "#d8c6a8", detail: "#2a2018", accent: "#8a7458" },
  },
  {
    id: "list",
    name: "List",
    species: "pes",
    feedGroup: "mazlici",
    personality: "Rozverné štěně, které moc rádo zkoumá a ochutnává.",
    fact: "Štěňata prozkoumávají svět tlamou — proto vše ochutnají. List se na Louce stále pohřešuje, vzpomínáme na něj.",
    palette: { body: "#e8dcc4", bodyDark: "#c8b48c", belly: "#f5eedd", detail: "#6a5a44", accent: "#b85c3c" },
    special: "missing",
  },
  {
    id: "roman",
    name: "Roman",
    species: "kocka",
    feedGroup: "mazlici",
    personality: "Nejsvalnatější kocour na celém světě.",
    fact: "Kočka má v každém uchu přes 20 svalů a otočí ušima skoro o 180°, aby zaměřila i tichý zvuk.",
    palette: { body: "#d98b3c", bodyDark: "#b06a22", belly: "#f0d6a8", detail: "#7a4a18", accent: "#3a2a14" },
    variant: "muscular",
  },
  {
    id: "safir",
    name: "Safír",
    species: "kocka",
    feedGroup: "mazlici",
    personality: "Nejchundelatější kocour na celém světě.",
    fact: "Kočky prospí 12–16 hodin denně, aby šetřily síly na lov. Předení je uklidňuje a podle studií i hojí.",
    palette: { body: "#6a7a8c", bodyDark: "#485668", belly: "#c2cdd8", detail: "#2a3038", accent: "#8a9aac" },
    variant: "shaggy",
  },
  {
    id: "patricie",
    name: "Patricie",
    species: "kocka",
    feedGroup: "mazlici",
    personality: "Nejumňoukanější kočka na celém světě.",
    fact: "Dospělé kočky mňoukají skoro výhradně na lidi — mezi sebou se baví spíš pachem a řečí těla.",
    palette: { body: "#e8e2d8", bodyDark: "#c0b6a6", belly: "#f5f0e8", detail: "#b85c3c", accent: "#3a3330" },
    variant: "calico",
  },
  {
    id: "hanicka",
    name: "Hanička",
    species: "kocka",
    feedGroup: "mazlici",
    personality: "Třínohá kočka samotářka.",
    fact: "Zvířata se zvládnou přizpůsobit i ztrátě nohy — Hanička běhá a šplhá po svém a nic jí nechybí.",
    palette: { body: "#3a3330", bodyDark: "#211c1a", belly: "#d8d0c4", detail: "#f0b8a8", accent: "#8a8276" },
    variant: "tripod",
  },
  {
    id: "lotka",
    name: "Lotka",
    species: "kocka",
    feedGroup: "mazlici",
    personality: "Kočka samotářka.",
    fact: "Každý kočičí nos má jedinečný otisk — stejně jako otisk prstu u člověka.",
    palette: { body: "#8a8276", bodyDark: "#5e574c", belly: "#c8c2b6", detail: "#3a3330", accent: "#46413a" },
    variant: "tabby",
  },
  {
    id: "masa",
    name: "Máša",
    species: "kocka",
    feedGroup: "mazlici",
    personality: "Luční modrooká blondýna.",
    fact: "Modré oči mívají kočky se světlou srstí — barvu očím dává množství pigmentu, ne plemeno.",
    palette: { body: "#ece0c4", bodyDark: "#d0c09c", belly: "#f7f0de", detail: "#6aa6c8", accent: "#b8a070" },
    variant: "blueeyes",
  },
  {
    id: "kralici",
    name: "Králíci",
    species: "kralik",
    feedGroup: "mazlici",
    personality: "Králíčci, co si užívají svobody.",
    fact: "Králíci dělají radostné výskoky zvané „binky“. Zuby jim rostou celý život, proto pořád něco okusují.",
    palette: { body: "#b09a82", bodyDark: "#836f58", belly: "#f0e8da", detail: "#d98c8c", accent: "#5a4a38" },
  },
];

export const ANIMAL_BY_ID: Record<string, AnimalDef> = Object.fromEntries(
  ANIMALS.map((a) => [a.id, a]),
);

export const ANIMALS_BY_GROUP = {
  drubez: ANIMALS.filter((a) => a.feedGroup === "drubez"),
  prasata: ANIMALS.filter((a) => a.feedGroup === "prasata"),
  stado: ANIMALS.filter((a) => a.feedGroup === "stado"),
  mazlici: ANIMALS.filter((a) => a.feedGroup === "mazlici"),
} as const;
